### ISSUE TITLE
Can we disable the spawning of some specific mobs?

### ISSUE THREAD

**Issue by ircmaan** [Wilyicaro/MoZombiesWave#2]
We need to turn off the spawn of some mobs. For example - Zombie Notch.
Thanx

**Comment by Wilyicaro** [comment]
You have to use BadMobs or InControl mod for now, maybe in future versions I'll add the possibility to configure mobs spawn.

**Comment by ircmaan** [comment]
Big Thanx!

2023-03-14 2:49 GMT+02:00, Wilyicaro ***@***.***>:
